baseURL: "https://pranavchendur.com"
languageCode: "en-us"
title: "PranavChendur"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "https://pc.fyi/twitter"
  github: "https://pc.fyi/github"
  instagram: "https://pc.fyi/instagram"
  linkedin: "https://pc.fyi/linkedin"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
