name: Deploy to Workers Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g

      - name: Build
        run: hugo --gc --minify

      - name: config wrangler
        run: | 
          CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} \
          CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} \
          CF_ZONE_ID=${{ secrets.CF_ZONE_ID }} \
          wrangler publish --env production
